# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'
platform :osx, '10.13'

target 'Example-SwiftUI' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example-SwiftUI
  pod 'CocoaUPnP', :path => '../CocoaUPnP.podspec'

end

# Xcode 10 generates a bunch of warnings when using CocoaPods
# when the deployment target of pods is set to lower than the
# project deployment target.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

